services:
  oci:
    container_name: oci
    image: sgrtye/oci:latest
    restart: unless-stopped
    networks:
      - oci
    volumes:
      - ${OCI_ENV_PATH}:/app/env

networks:
  oci:
    driver: bridge