services:
  oci:
    container_name: oci
    image: ${APP_IMAGE:-sgrtye/oci:latest}
    restart: unless-stopped
    networks:
      - oci
    volumes:
      - ${OCI_ENV_PATH}:/app/env:ro

networks:
  oci:
    driver: bridge