services:
  uptimekuma:
    container_name: uptimekuma
    image: ${APP_IMAGE:-louislam/uptime-kuma:2-slim}
    restart: unless-stopped
    ports:
      - 3001:3001
    networks:
      - uptimekuma
    volumes:
      - data:/app/data:rw

volumes:
  data:

networks:
  uptimekuma:
    driver: bridge