services:
  vaultwarden:
    container_name: vaultwarden
    image: ${APP_IMAGE:-vaultwarden/server:latest}
    restart: unless-stopped
    ports:
      - 888:80
    networks:
      - vaultwarden
    volumes:
      - data:/data:rw
    environment:
      - SIGNUPS_ALLOWED=${SIGNUPS_ALLOWED}

volumes:
  data:

networks:
  vaultwarden:
    driver: bridge