services:
  x-ui:
    container_name: x-ui
    image: alireza7/x-ui:latest
    hostname: ${XUI_HOSTNAME}
    restart: unless-stopped
    volumes:
      - ${XUI_DATABASE_PATH}:/etc/x-ui
    environment:
      - TZ=${TZ}
      - XRAY_VMESS_AEAD_FORCED=${XRAY_VMESS_AEAD_FORCED}

  xuiserver:
    container_name: xuiserver
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 8088:80
    volumes:
      - ${HTML_PATH}:/var/www/html
      - ${NGINX_CONFIG_PATH}:/etc/nginx/conf.d

  submanager:
    container_name: submanager
    image: sgrtye/submanager:latest
    restart: unless-stopped
    volumes:
      - ${SUB_PATH}:/sub
      - ${NGINX_CONFIG_PATH}:/conf.d
    environment:
      - XUI_USERNAME=${XUI_USERNAME}
      - XUI_PASSWORD=${XUI_PASSWORD}
      - XUI_URL=${XUI_URL}
      - HOST_DOMAIN=${HOST_DOMAIN}
      - MITCE_URL=${MITCE_URL}