services:
  traefik:
    container_name: traefik
    image: ${APP_IMAGE:-traefik:v3}
    restart: unless-stopped
    ports:
      - 8888:8888
    networks:
      - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${TRAEFIK_CONFIG_PATH}:/etc/traefik/traefik.yaml:ro
      - ${TRAEFIK_CERTS_PATH}:/var/traefik/certs:rw
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}

networks:
  traefik:
    driver: bridge