services:
  traefik:
    container_name: traefik
    image: traefik:v3
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      # - 8080:8080
    networks:
      - traefik
      - gateway
    volumes:
      - ${DOCKER_SOCK}:/run/docker.sock:ro
      - ${TRAEFIK_CONFIG_PATH}:/etc/traefik/traefik.yaml:ro
      - ${TRAEFIK_CERTS_PATH}:/var/traefik/certs:rw
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    labels:
      - traefik.enable=true
      - traefik.docker.network=gateway
      - traefik.http.routers.traefik-http.entrypoints=http
      - traefik.http.routers.traefik-http.rule=${HOST_RULE}
      - traefik.http.routers.traefik-http.middlewares=auth-v1@file
      - traefik.http.routers.traefik-https.service=api@internal
      - traefik.http.routers.traefik-https.entrypoints=https
      - traefik.http.routers.traefik-https.rule=${HOST_RULE}
      - traefik.http.routers.traefik-https.middlewares=auth-v1@file
      - traefik.http.routers.traefik-https.service=api@internal
      - traefik.http.routers.traefik-https.tls=true
      - traefik.http.routers.traefik-https.tls.certresolver=cloudflare

networks:
  traefik:
    driver: bridge
  gateway:
    external: true