services:
  wordpress:
    container_name: wordpress
    image: wordpress:latest
    restart: unless-stopped
    ports:
      - 80:80
    networks:
      - wordpress
      - gateway
    volumes:
      - ${HTML_PATH}:/var/www/html:rw
    environment:
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - WORDPRESS_CONFIG_EXTRA=${WORDPRESS_CONFIG_EXTRA}
    labels:
      - traefik.enable=true
      - traefik.http.services.wordpress.loadbalancer.server.port=80
      - traefik.http.routers.wordpress-http.entrypoints=http
      - traefik.http.routers.wordpress-http.rule=${HOST_RULE}
      - traefik.http.routers.wordpress-https.entrypoints=https
      - traefik.http.routers.wordpress-https.rule=${HOST_RULE}
      - traefik.http.routers.wordpress-https.tls=true
      - traefik.http.routers.wordpress-https.tls.certresolver=cloudflare

  db:
    container_name: database
    image: mariadb:latest
    restart: unless-stopped
    networks:
      - wordpress
    volumes: 
      - ${MYSQL_PATH}:/var/lib/mysql:rw
    environment:
      - MYSQL_DATABASE=${WORDPRESS_DB_NAME}
      - MYSQL_USER=${WORDPRESS_DB_USER}
      - MYSQL_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

  redis:
    container_name: redis
    image: redis:latest
    restart: unless-stopped
    networks:
      - wordpress
    volumes: 
      - ${REDIS_PATH}:/data:rw

networks:
  wordpress:
    driver: bridge
  gateway:
    external: true