services:
  wordpress:
    container_name: wordpress
    image: wordpress:latest
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ${HTML_PATH}:/var/www/html
    environment:
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - WORDPRESS_CONFIG_EXTRA=${WORDPRESS_CONFIG_EXTRA}

  db:
    container_name: database
    image: mariadb:latest
    restart: unless-stopped
    volumes: 
      - ${MYSQL_PATH}:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${WORDPRESS_DB_NAME}
      - MYSQL_USER=${WORDPRESS_DB_USER}
      - MYSQL_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

  redis:
    container_name: redis
    image: redis:latest
    restart: unless-stopped
    volumes: 
      - ${REDIS_PATH}:/data