services:
  portainer:
    container_name: portainer
    image: ${APP_IMAGE:-portainer/portainer-ee:sts}
    restart: unless-stopped
    ports:
      - 9000:9000
    networks:
      - portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - ${PORTAINER_DATA_PATH}:/data:rw

networks:
  portainer:
    driver: bridge