services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ee:sts
    restart: unless-stopped
    ports:
      - 9443:9443
    networks:
      - portainer
      - gateway
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - ${PORTAINER_DATA_PATH}:/data:rw
    labels:
      - traefik.enable=true
      - traefik.docker.network=gateway
      - traefik.http.services.portainer.loadbalancer.server.port=9443
      - traefik.http.services.portainer.loadbalancer.server.scheme=https
      - traefik.http.routers.portainer-http.entrypoints=http
      - traefik.http.routers.portainer-http.rule=${HOST_RULE}
      - traefik.http.routers.portainer-https.entrypoints=https
      - traefik.http.routers.portainer-https.rule=${HOST_RULE}
      - traefik.http.routers.portainer-https.tls=true
      - traefik.http.routers.portainer-https.tls.certresolver=cloudflare

networks:
  portainer:
    driver: bridge
  gateway:
    external: true