services:
  wireguard:
    container_name: wireguard
    image: lscr.io/linuxserver/wireguard:latest
    restart: unless-stopped
    ports:
      - 51820:51820/udp
    networks:
      - wireguard
    environment:
      - PUID=1000
      - PGID=1000
      - PEERS=3
      - TZ=${TZ}
    volumes:
      - ${WIREGUARD_CONFIG_PATH}:/config:rw
      - /lib/modules:/lib/modules:ro
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1

networks:
  wireguard:
    driver: bridge