name: Sync pushes to Gitee

on:
  push:
  delete:
  workflow_dispatch:

jobs:
  Sync:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Sync repo to Gitee
        env:
          GITEE_TOKEN: ${{ secrets.GITEE_TOKEN }}
        run: |
          git remote add gitee https://sgrtye:${GITEE_TOKEN}@gitee.com/sgrtye/docker-compose.git
          git push gitee --mirror